version: "3"
services:
  express-server:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/app
      # - /app/node_modules
    environment: 
      - NODE_ENV=development
    command: npm run dev